### ISSUE TITLE
Range issue with /guard

### ISSUE THREAD

**Issue by ShadowSplicer** [jrbudda/Sentry#181]
I run a server where I provide 'adoptable' pets, and use T00thTransaction to manage the 'purchases.' On login, the package manager runs a series of commands to create an NPC with specific stats (spawns on my main world spawn), and then is <i>supposed</i> to 'guard' the player who purchased it. Only problem is that the NPC can't find the player in range, unless they're _standing_ inside spawn when they use it. 
I'd love to avoid this issue. I've tried warping the player to spawn as the first command action, but it applies _after_ the creation commands process. I've also tried teleporting the NPC to the player, and the player to the NPC. I can't find any way of getting the NPC to guard the player at all!

Is there a way to modify the code so that the Sentry gets teleported to the target player if it isn't in range onCommand?

**Comment by mcmonkey4eva** [comment]
@ShadowSplicer - few things:
- you could just spawn the NPC next to the player, couldn't you?
- If not, I recommend using something like [Denizen](http://wiki.citizensnpcs.co/Denizen) to handle it
- but either way, I will correct that bug and ensure they teleport when I can get around to it.

**Comment by ShadowSplicer** [comment]
Thanks for the quick reply.

<ul>
  <li>No, there isn't a way of spawning at player: just a location x:y:z:world</li>
  <li>Denizen doesn't have anything for this, already tried searching.</li>
  <li>That would be helpful! Thanks!</li>
</ul>

**Comment by mcmonkey4eva** [comment]
@ShadowSplicer - Denizen most /definitely/ can do this!
here's an example Denizen script to do it:

```
buystuff:
  type: world
  events:
    on buystuff command:
    - if <player.money> < 5 {
      - narrate "Not enough moneys"
      - queue clear
      }
    - take money qty:5
    - execute as_server "npc create kitty --at <player.location.formatted.citizens> --trait sentry"
    - execute as_server "sentry guard <player.name>"
```
